version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/service_stop.sh
      runas: root
#  AfterInstall:
#    - location: scripts/change_permissions.sh
#      runas: root
  ApplicationStart:
    - location: scripts/service_stop.sh
      runas: root